# Change these first
owner: kreisklasse # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: A310.net
    url: https://a310.net/
  - name: Time.is
    url: https://time.is
  - name: protective.joindns4.eu DNS ipv4 DOH
    url: protective.joindns4.eu
    check: "tcp-ping"
    port: 443
  - name: protective.joindns4.eu DNS ipv6 DOH
    url: protective.joindns4.eu
    check: "tcp-ping"
    port: 443
    ipv6: true
  - name: freedns.controld.com DNS ipv4 DOH
    url: freedns.controld.com
    check: "tcp-ping"
    port: 443
  - name: freedns.controld.com DNS ipv6 DOH
    url: freedns.controld.com
    check: "tcp-ping"
    port: 443
    ipv6: true
  - name: ffmuc.net DNS ipv4 DOH
    url: doh.ffmuc.net
    check: "tcp-ping"
    port: 443
  - name: ffmuc.net DNS ipv6 DOH
    url: doh.ffmuc.net
    check: "tcp-ping"
    port: 443
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
